[package]
name = "factorion-bot"
version = "1.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "^0.14.0"
reqwest = { version = "^0.12.9", features = ["json"] }
serde = { version = "^1.0.216", features = ["derive"] }
serde_json = "^1.0.133"
tokio = { version = "^1.42.0", features = ["full"] }
num-traits = "^0.2.19"
base64 = "^0.22.1"
dotenv = "^0.15.0"
time = "^0.3.37"
chrono = "^0.4.38"
num-bigint = "0.4.6"
anyhow = "1.0.94"