[package]
name = "factorion-bot"
version = "1.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "^0.14.0"
reqwest = { version = "^0.12.12", features = ["json"] }
serde = { version = "^1.0.217", features = ["derive"] }
serde_json = "^1.0.134"
tokio = { version = "^1.42.0", features = ["full"] }
num-traits = "^0.2.19"
base64 = "^0.22.1"
dotenv = "^0.15.0"
time = "^0.3.37"
chrono = "^0.4.39"
num-bigint = "0.4.6"
anyhow = "1.0.95"
http = "1.2.0"
influxdb = { version = "0.7.2", features = ["derive"] }
once_cell = "1.10.0"