[package]
name = "factorion-bot"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "^0.14"
reqwest = { version = "^0.12", features = ["json"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "^1.37.0", features = ["full"] }
num-bigint = "^0.4"
num-traits = "^0.2"
base64 = "^0.22"
dotenv = "^0.15"
time = "0.3"
