version: "3.8"

services:
  factorion-bot:
    image: factorion-bot:${VERSION}
    container_name: factorion-bot
    volumes:
      - ${SSH_PATH}:/usr/factorion
      - /var/log/factorion:/var/log/factorion
    networks:
      - service-network
    restart: unless-stopped
    command: sh -c "./run.sh 2>&1 | tee /var/log/factorion-bot/logfile-${VERSION}.log"

networks:
  service-network:
    external: true
