[package]
name = "factorion-lib"
version = "1.0.0"
edition = "2024"

[dependencies]
factorion-math = {path = "../factorion-math", version = "1.0"}
rug = { version = "1.27.0", features = ["integer", "float"], default-features = false }
gmp-mpfr-sys = "=1.6.4"

[dev-dependencies]
arbtest = "0.3.2"
