[package]
name = "factorion-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
factorion-math = {path = "../factorion-math"}
rug = { version = "1.27.0", features = ["integer", "float"], default-features = false }

[dev-dependencies]
arbtest = "0.3.2"
