name: Deploy to Server

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem # Write the private key to a file
          chmod 600 private_key.pem # Set the appropriate permissions for the key file

          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd services/factorion-bot && \
            git fetch origin master && \
            git reset --hard origin/master && \
            docker kill factorion-bot && \
            docker build -t factorion-bot . && \
            docker run --rm -d --network service-network --name factorion-bot --volume ${PWD}:/usr/factorion factorion-bot:latest"
          
          rm -f private_key.pem # Remove the private key file after use for security
