name: Machete

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Machete
        uses: bnjbvr/cargo-machete@v0.7.0

